### ISSUE TITLE
Theme.css does not load correctly

### ISSUE THREAD

**Issue by auditio** [ThisNetWorks/ThisNetWorks.OrchardCore.Themes#1]
As soon as I enable these theme, even when The Admin theme is currently in use, my UI breaks. The same issue occurs if I set ThisNetWorksAdminTheme as my current theme

The following console error is thrown:

> ContentItems?admin=-825613234:19 GET https://localhost:44300/ThisNetWorksAdminTheme/Styles/theme.css net::ERR_ABORTED 404

This is the reference that needs to be resolved:

> href="/ThisNetWorksAdminTheme/Styles/theme.css" rel="stylesheet" type="text/css"

**Comment by deanmarcussen** [comment]
This should be fixed now on master
